name: Build and deploy Node.js app to Azure Web App - ETSFrontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build

      - name: Prepare standalone artifact
        run: |
          mkdir deploy
          cp -r .next/standalone/* deploy/
          cp -r .next/static deploy/.next/static
          cp -r public deploy/public

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: next-build

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: ETSFrontend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B4067C4C726A499DBC69101B496FD154 }}
          package: .
